FROM nexus.medmakers.io/docker/flutter:3.44.6 AS builder

WORKDIR /src
COPY emulator_orchestrator emulator_orchestrator
COPY emulator_ui emulator_ui
COPY pubspec.yaml pubspec.yaml
COPY pubspec.lock pubspec.lock

RUN flutter pub get && \
    cd emulator_orchestrator && \
    dart run build_runner build --delete-conflicting-outputs && \
    cd ../emulator_ui && \
    flutter build linux 

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    binutils-arm-none-eabi \
    libsqlite3-dev \
    gosu \
    libgtk-3-dev \
    liblzma-dev \
    xvfb \
    x11vnc \
    zenity \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /src/emulator_ui/build/linux/x64/release/bundle /app
ENV PATH="/app:${PATH}"
WORKDIR /app
COPY docker/resect-gui.config /resect.config
ENV RESECT_CONFIG=/resect.config

COPY docker/gui-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["resect"]