name: resect_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

# Add regular dependencies here.
dependencies:
  callgraph: {git: git@github.com:IoMT-Lab/callgraph-dart.git}
  logging: ^1.3.0
  path: ^1.9.1
  renode: {git: git@github.com:IoMT-Lab/renode-dart.git}
  

dev_dependencies:
  iomt_lab_lints: {git: git@github.com:IoMT-Lab/lints-dart.git}
